# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  sonata.admin.dictionary_bank:
          class: AppBundle\Admin\DictionaryBankAdmin
          arguments: [~, AppBundle\Entity\DictionaryBank, 'SonataAdminBundle:CRUD']
          tags:
              - { name: sonata.admin, manager_type: orm, group: sonata.admin.group.content, label: Справочник банков }
          calls:
              - [ setTranslationDomain, [AppBundle]]

  sonata.admin.dictionary_organization:
          class: AppBundle\Admin\OrganizationAdmin
          arguments: [~, AppBundle\Entity\Organization, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: sonata.admin.group.content, label: Справочник организаций }

  sonata.admin.dictionary_ministry:
          class: AppBundle\Admin\DictionaryMinistryAdmin
          arguments: [~, AppBundle\Entity\DictionaryMinistry, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: sonata.admin.group.content, label: Справочник министерств (ведомств) }

  sonata.admin.dictionary_facility:
          class: AppBundle\Admin\FacilityAdmin
          arguments: [~, AppBundle\Entity\Facility, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: sonata.admin.group.content, label: Справочник объектов }

  api_key_user_provider:
      class: AppBundle\Security\ApiKeyUserProvider

  apikey_authenticator:
      class:  AppBundle\Security\ApiKeyAuthenticator
      arguments: ["@api_key_user_provider"]
      public: false