services:
      app.soft_delete_subscriber:
          class: AppBundle\EventSubscriber\SoftDeleteSubscriber
          arguments: []
          tags:
              - { name: doctrine.event_subscriber, connection: default }